version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    env_file: postgres.env
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    image: horobot:latest
    restart: always
    env_file:
      - bot.env
      - postgres.env
    container_name: bot
    depends_on:
      - postgres

volumes:
  data: