version: "3.8"
services:
  gateway:
    image: winteryfox/mizore-gateway
    depends_on: [gateway-rabbitmq]
  gateway-rabbitmq:
    image: rabbitmq:3.9.25-alpine
    ports:
      - "5672:5672"
      - "15672:8080"
  bot:
    image: winteryfox/mizore-bot
    depends_on: [gateway]
