version: "3.0"

services:
  postgres:
    image: postgres:13
    restart: always
    env_file: postgres.yml
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.0.5
    restart: always
    container_name: redis

  bot:
    image: winteryfox/horobot:latest
    restart: always
    env_file:
      - bot.yml
      - postgres.yml
    container_name: bot
    depends_on:
      - postgres
      - redis

volumes:
  data: