apiVersion: apps/v1
kind: Deployment
metadata:
  name: horobot
  labels:
    app: horo
spec:
  selector:
    matchLabels:
      app: horo
  template:
    metadata:
      name: HoroBot
      labels:
        app: horo
    spec:
      containers:
        - name: bot
          image: winteryfox/horobot:latest
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          envFrom:
            - secretRef:
                name: horo-bot
        - name: postgres
          image: postgres:13
          envFrom:
            - secretRef:
                name: horo-postgres
        - name: redis
          image: redis:6.0.8
          resources:
            limits:
              memory: "3Gi"
            requests:
              memory: "1Gi"